name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/head/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          TOKEN: ${{ secrets.TOKEN }}
  
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - uses: actions/checkout@v2

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
